-- NovaWave Business ERP - schema inicial PostgreSQL 15+
-- Destinado a bancos novos. Alteracoes futuras devem usar migrations versionadas.

BEGIN;

-- =========================================================
-- PLATAFORMA E SAAS
-- =========================================================

CREATE TABLE public.platform_usuario (
  idplatform_usuario integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar(150) NOT NULL,
  email varchar(150) NOT NULL,
  senha_hash varchar(255) NOT NULL,
  telefone varchar(30),
  cargo varchar(100),
  nivel_acesso varchar(20) NOT NULL DEFAULT 'super_admin',
  avatar_url varchar(255),
  ultimo_login timestamp,
  situacao smallint NOT NULL DEFAULT 1,
  criado_em timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em timestamp,
  CONSTRAINT ck_platform_usuario_situacao CHECK (situacao IN (0, 1)),
  CONSTRAINT ck_platform_usuario_nivel CHECK (
    nivel_acesso IN ('super_admin', 'suporte', 'financeiro', 'comercial', 'leitura')
  ),
  CONSTRAINT uq_platform_usuario_email UNIQUE (email)
);

CREATE UNIQUE INDEX uq_platform_usuario_email_normalizado
  ON public.platform_usuario (LOWER(BTRIM(email)));

CREATE TABLE public.platform_login_tentativa (
  idtentativa integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email varchar(150) NOT NULL,
  ip varchar(50),
  sucesso boolean NOT NULL DEFAULT false,
  criado_em timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_platform_login_bloqueio
  ON public.platform_login_tentativa (LOWER(BTRIM(email)), ip, criado_em)
  WHERE sucesso = false;

CREATE TABLE public.platform_configuracao (
  idconfiguracao integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chave varchar(100) NOT NULL,
  valor jsonb NOT NULL DEFAULT '{}'::jsonb,
  grupo varchar(50) NOT NULL,
  segredo boolean NOT NULL DEFAULT false,
  atualizado_por integer,
  criado_em timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em timestamp,
  CONSTRAINT fk_platform_config_usuario FOREIGN KEY (atualizado_por)
    REFERENCES public.platform_usuario(idplatform_usuario)
    ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT uq_platform_config_chave UNIQUE (chave)
);

CREATE TABLE public.plano (
  idplano integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar(100) NOT NULL,
  descricao varchar(500),
  valor_mensal numeric(10,2) NOT NULL DEFAULT 0,
  valor_anual numeric(10,2) NOT NULL DEFAULT 0,
  limite_usuarios integer,
  limite_filiais integer,
  limite_produtos integer,
  limite_armazenamento_mb integer,
  modulos jsonb NOT NULL DEFAULT '{}'::jsonb,
  situacao smallint NOT NULL DEFAULT 1,
  criado_em timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em timestamp,
  CONSTRAINT ck_plano_valores CHECK (valor_mensal >= 0 AND valor_anual >= 0),
  CONSTRAINT ck_plano_limites CHECK (
    (limite_usuarios IS NULL OR limite_usuarios >= 0) AND
    (limite_filiais IS NULL OR limite_filiais >= 0) AND
    (limite_produtos IS NULL OR limite_produtos >= 0) AND
    (limite_armazenamento_mb IS NULL OR limite_armazenamento_mb >= 0)
  ),
  CONSTRAINT ck_plano_situacao CHECK (situacao IN (0, 1)),
  CONSTRAINT uq_plano_nome UNIQUE (nome)
);

CREATE TABLE public.empresa (
  idempresa integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razao_social varchar(150) NOT NULL,
  nome_fantasia varchar(150) NOT NULL,
  cnpj varchar(18),
  inscricao_estadual varchar(30),
  email varchar(150),
  telefone varchar(30),
  cep varchar(20),
  endereco varchar(150),
  numero varchar(20),
  complemento varchar(100),
  bairro varchar(100),
  cidade varchar(100),
  estado varchar(2),
  logo_url varchar(255),
  favicon_url varchar(255),
  cor_primaria varchar(7) NOT NULL DEFAULT '#2F80FF',
  cor_secundaria varchar(7) NOT NULL DEFAULT '#4F46E5',
  timezone varchar(60) NOT NULL DEFAULT 'America/Sao_Paulo',
  moeda varchar(3) NOT NULL DEFAULT 'BRL',
  idioma varchar(10) NOT NULL DEFAULT 'pt-BR',
  situacao smallint NOT NULL DEFAULT 1,
  criado_em timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em timestamp,
  CONSTRAINT ck_empresa_situacao CHECK (situacao IN (0, 1, 2)),
  CONSTRAINT ck_empresa_cores CHECK (
    cor_primaria ~ '^#[0-9A-Fa-f]{6}$' AND cor_secundaria ~ '^#[0-9A-Fa-f]{6}$'
  ),
  CONSTRAINT uq_empresa_cnpj UNIQUE (cnpj),
  CONSTRAINT uq_empresa_idempresa UNIQUE (idempresa)
);

CREATE TABLE public.assinatura (
  idassinatura integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  idempresa integer NOT NULL,
  idplano integer NOT NULL,
  data_inicio date NOT NULL,
  data_fim date,
  data_proxima_cobranca date,
  status smallint NOT NULL DEFAULT 2,
  forma_pagamento varchar(50),
  valor_atual numeric(10,2) NOT NULL DEFAULT 0,
  criado_em timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em timestamp,
  CONSTRAINT fk_assinatura_empresa FOREIGN KEY (idempresa)
    REFERENCES public.empresa(idempresa) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_assinatura_plano FOREIGN KEY (idplano)
    REFERENCES public.plano(idplano) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT ck_assinatura_status CHECK (status IN (1, 2, 3, 4, 5)),
  CONSTRAINT ck_assinatura_valor CHECK (valor_atual >= 0),
  CONSTRAINT ck_assinatura_datas CHECK (data_fim IS NULL OR data_fim >= data_inicio)
);

-- =========================================================
-- ESTRUTURA ORGANIZACIONAL
-- =========================================================

CREATE TABLE public.filial (
  idfilial integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  idempresa integer NOT NULL,
  nome varchar(150) NOT NULL,
  codigo varchar(50) NOT NULL,
  cnpj varchar(18),
  inscricao_estadual varchar(30),
  email varchar(150),
  telefone varchar(30),
  cep varchar(20),
  endereco varchar(150),
  numero varchar(20),
  complemento varchar(100),
  bairro varchar(100),
  cidade varchar(100),
  estado varchar(2),
  matriz boolean NOT NULL DEFAULT false,
  idgerente integer,
  latitude numeric(9,6),
  longitude numeric(9,6),
  permite_estoque_negativo boolean NOT NULL DEFAULT false,
  caixa_obrigatorio boolean NOT NULL DEFAULT true,
  situacao smallint NOT NULL DEFAULT 1,
  criado_em timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em timestamp,
  CONSTRAINT fk_filial_empresa FOREIGN KEY (idempresa)
    REFERENCES public.empresa(idempresa) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT ck_filial_situacao CHECK (situacao IN (0, 1)),
  CONSTRAINT ck_filial_coordenadas CHECK (
    (latitude IS NULL OR latitude BETWEEN -90 AND 90) AND
    (longitude IS NULL OR longitude BETWEEN -180 AND 180)
  ),
  CONSTRAINT uq_filial_empresa_idfilial UNIQUE (idempresa, idfilial),
  CONSTRAINT uq_filial_empresa_codigo UNIQUE (idempresa, codigo),
  CONSTRAINT uq_filial_empresa_nome UNIQUE (idempresa, nome)
);

CREATE UNIQUE INDEX uq_filial_matriz_empresa
  ON public.filial(idempresa) WHERE matriz = true;

CREATE TABLE public.departamento (
  iddepartamento integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  idempresa integer NOT NULL,
  nome varchar(100) NOT NULL,
  descricao varchar(255),
  situacao smallint NOT NULL DEFAULT 1,
  criado_em timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em timestamp,
  CONSTRAINT fk_departamento_empresa FOREIGN KEY (idempresa)
    REFERENCES public.empresa(idempresa) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT ck_departamento_situacao CHECK (situacao IN (0, 1)),
  CONSTRAINT uq_departamento_empresa_id UNIQUE (idempresa, iddepartamento),
  CONSTRAINT uq_departamento_empresa_nome UNIQUE (idempresa, nome)
);

CREATE TABLE public.cargo (
  idcargo integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  idempresa integer NOT NULL,
  iddepartamento integer,
  nome varchar(100) NOT NULL,
  descricao varchar(255),
  salario_base numeric(10,2) NOT NULL DEFAULT 0,
  situacao smallint NOT NULL DEFAULT 1,
  criado_em timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em timestamp,
  CONSTRAINT fk_cargo_empresa FOREIGN KEY (idempresa)
    REFERENCES public.empresa(idempresa) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_cargo_departamento FOREIGN KEY (idempresa, iddepartamento)
    REFERENCES public.departamento(idempresa, iddepartamento)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT ck_cargo_salario CHECK (salario_base >= 0),
  CONSTRAINT ck_cargo_situacao CHECK (situacao IN (0, 1)),
  CONSTRAINT uq_cargo_empresa_id UNIQUE (idempresa, idcargo),
  CONSTRAINT uq_cargo_empresa_nome UNIQUE (idempresa, nome)
);

CREATE TABLE public.funcionario (
  idfuncionario integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  idempresa integer NOT NULL,
  idfilial integer NOT NULL,
  idcargo integer,
  nome varchar(150) NOT NULL,
  cpf varchar(14),
  email varchar(150),
  telefone varchar(30),
  salario numeric(10,2) NOT NULL DEFAULT 0,
  data_admissao date,
  data_demissao date,
  situacao smallint NOT NULL DEFAULT 1,
  criado_em timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em timestamp,
  CONSTRAINT fk_funcionario_empresa FOREIGN KEY (idempresa)
    REFERENCES public.empresa(idempresa) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_funcionario_filial FOREIGN KEY (idempresa, idfilial)
    REFERENCES public.filial(idempresa, idfilial) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_funcionario_cargo FOREIGN KEY (idempresa, idcargo)
    REFERENCES public.cargo(idempresa, idcargo) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT ck_funcionario_salario CHECK (salario >= 0),
  CONSTRAINT ck_funcionario_datas CHECK (
    data_demissao IS NULL OR data_admissao IS NULL OR data_demissao >= data_admissao
  ),
  CONSTRAINT ck_funcionario_situacao CHECK (situacao IN (0, 1)),
  CONSTRAINT uq_funcionario_empresa_id UNIQUE (idempresa, idfuncionario),
  CONSTRAINT uq_funcionario_empresa_cpf UNIQUE (idempresa, cpf)
);

CREATE TABLE public.usuario (
  idusuario integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  idempresa integer NOT NULL,
  idfilial_padrao integer,
  idfuncionario integer,
  nome varchar(150) NOT NULL,
  email varchar(150) NOT NULL,
  senha_hash varchar(255) NOT NULL,
  telefone varchar(30),
  avatar_url varchar(255),
  admin_empresa boolean NOT NULL DEFAULT false,
  ultimo_login timestamp,
  situacao smallint NOT NULL DEFAULT 1,
  criado_em timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em timestamp,
  CONSTRAINT fk_usuario_empresa FOREIGN KEY (idempresa)
    REFERENCES public.empresa(idempresa) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_usuario_filial_padrao FOREIGN KEY (idempresa, idfilial_padrao)
    REFERENCES public.filial(idempresa, idfilial) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_usuario_funcionario FOREIGN KEY (idempresa, idfuncionario)
    REFERENCES public.funcionario(idempresa, idfuncionario)
    ON UPDATE CASCADE ON DELETE SET NULL (idfuncionario),
  CONSTRAINT ck_usuario_situacao CHECK (situacao IN (0, 1)),
  CONSTRAINT uq_usuario_empresa_id UNIQUE (idempresa, idusuario),
  CONSTRAINT uq_usuario_empresa_email UNIQUE (idempresa, email),
  CONSTRAINT uq_usuario_empresa_funcionario UNIQUE (idempresa, idfuncionario)
);

-- O login inicial usa apenas e-mail e senha; portanto o e-mail precisa identificar
-- inequivocamente um usuario entre todos os tenants.
CREATE UNIQUE INDEX uq_usuario_email_normalizado
  ON public.usuario (LOWER(BTRIM(email)));

ALTER TABLE public.filial
  ADD CONSTRAINT fk_filial_gerente
  FOREIGN KEY (idempresa, idgerente)
  REFERENCES public.usuario(idempresa, idusuario)
  ON UPDATE CASCADE ON DELETE SET NULL (idgerente);

-- =========================================================
-- ACESSO, PREFERENCIAS E DASHBOARD
-- =========================================================

CREATE TABLE public.perfil_acesso (
  idperfil integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  idempresa integer NOT NULL,
  nome varchar(100) NOT NULL,
  descricao varchar(255),
  escopo smallint NOT NULL DEFAULT 1,
  situacao smallint NOT NULL DEFAULT 1,
  criado_em timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em timestamp,
  CONSTRAINT fk_perfil_empresa FOREIGN KEY (idempresa)
    REFERENCES public.empresa(idempresa) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT ck_perfil_escopo CHECK (escopo IN (1, 2)),
  CONSTRAINT ck_perfil_situacao CHECK (situacao IN (0, 1)),
  CONSTRAINT uq_perfil_empresa_id UNIQUE (idempresa, idperfil),
  CONSTRAINT uq_perfil_empresa_nome UNIQUE (idempresa, nome)
);

CREATE TABLE public.permissao (
  idpermissao integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  modulo varchar(100) NOT NULL,
  acao varchar(100) NOT NULL,
  descricao varchar(255),
  criado_em timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_permissao_modulo_acao UNIQUE (modulo, acao)
);

CREATE TABLE public.usuario_perfil (
  idusuario_perfil integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  idempresa integer NOT NULL,
  idusuario integer NOT NULL,
  idperfil integer NOT NULL,
  idfilial integer,
  criado_em timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_usuario_perfil_usuario FOREIGN KEY (idempresa, idusuario)
    REFERENCES public.usuario(idempresa, idusuario) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_usuario_perfil_perfil FOREIGN KEY (idempresa, idperfil)
    REFERENCES public.perfil_acesso(idempresa, idperfil) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_usuario_perfil_filial FOREIGN KEY (idempresa, idfilial)
    REFERENCES public.filial(idempresa, idfilial) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT uq_usuario_perfil UNIQUE (idempresa, idusuario, idperfil, idfilial)
);

CREATE UNIQUE INDEX uq_usuario_perfil_sem_filial
  ON public.usuario_perfil(idempresa, idusuario, idperfil) WHERE idfilial IS NULL;

CREATE TABLE public.perfil_permissao (
  idperfil_permissao integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  idempresa integer NOT NULL,
  idperfil integer NOT NULL,
  idpermissao integer NOT NULL,
  criado_em timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_perfil_permissao_perfil FOREIGN KEY (idempresa, idperfil)
    REFERENCES public.perfil_acesso(idempresa, idperfil) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_perfil_permissao_permissao FOREIGN KEY (idpermissao)
    REFERENCES public.permissao(idpermissao) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT uq_perfil_permissao UNIQUE (idempresa, idperfil, idpermissao)
);

CREATE TABLE public.usuario_filial (
  idusuario_filial integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  idempresa integer NOT NULL,
  idusuario integer NOT NULL,
  idfilial integer NOT NULL,
  criado_em timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_usuario_filial_usuario FOREIGN KEY (idempresa, idusuario)
    REFERENCES public.usuario(idempresa, idusuario) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_usuario_filial_filial FOREIGN KEY (idempresa, idfilial)
    REFERENCES public.filial(idempresa, idfilial) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT uq_usuario_filial UNIQUE (idempresa, idusuario, idfilial)
);

CREATE TABLE public.usuario_preferencia (
  idusuario_preferencia integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  idempresa integer NOT NULL,
  idusuario integer NOT NULL,
  tema varchar(10) NOT NULL DEFAULT 'system',
  idioma varchar(10) NOT NULL DEFAULT 'pt-BR',
  timezone varchar(60) NOT NULL DEFAULT 'America/Sao_Paulo',
  idfilial_padrao integer,
  dashboard_escopo_padrao varchar(10) NOT NULL DEFAULT 'empresa',
  sidebar_recolhida boolean NOT NULL DEFAULT false,
  criado_em timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em timestamp,
  CONSTRAINT fk_preferencia_usuario FOREIGN KEY (idempresa, idusuario)
    REFERENCES public.usuario(idempresa, idusuario) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_preferencia_filial FOREIGN KEY (idempresa, idfilial_padrao)
    REFERENCES public.filial(idempresa, idfilial) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT ck_preferencia_tema CHECK (tema IN ('light', 'dark', 'system')),
  CONSTRAINT ck_preferencia_dashboard CHECK (dashboard_escopo_padrao IN ('empresa', 'filial')),
  CONSTRAINT uq_preferencia_usuario UNIQUE (idempresa, idusuario)
);

CREATE TABLE public.dashboard_widget (
  idwidget integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo varchar(100) NOT NULL,
  nome varchar(100) NOT NULL,
  descricao varchar(255),
  modulo varchar(100) NOT NULL,
  situacao smallint NOT NULL DEFAULT 1,
  criado_em timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_dashboard_widget_situacao CHECK (situacao IN (0, 1)),
  CONSTRAINT uq_dashboard_widget_codigo UNIQUE (codigo)
);

CREATE TABLE public.usuario_dashboard_widget (
  idusuario_dashboard_widget integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  idempresa integer NOT NULL,
  idusuario integer NOT NULL,
  idwidget integer NOT NULL,
  posicao_x integer NOT NULL DEFAULT 0,
  posicao_y integer NOT NULL DEFAULT 0,
  largura integer NOT NULL DEFAULT 1,
  altura integer NOT NULL DEFAULT 1,
  visivel boolean NOT NULL DEFAULT true,
  configuracao jsonb NOT NULL DEFAULT '{}'::jsonb,
  criado_em timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em timestamp,
  CONSTRAINT fk_usuario_widget_usuario FOREIGN KEY (idempresa, idusuario)
    REFERENCES public.usuario(idempresa, idusuario) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_usuario_widget_widget FOREIGN KEY (idwidget)
    REFERENCES public.dashboard_widget(idwidget) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT ck_usuario_widget_dimensoes CHECK (
    posicao_x >= 0 AND posicao_y >= 0 AND largura > 0 AND altura > 0
  ),
  CONSTRAINT uq_usuario_dashboard_widget UNIQUE (idempresa, idusuario, idwidget)
);

CREATE TABLE public.sessao_usuario (
  idsessao integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  idempresa integer NOT NULL,
  idusuario integer NOT NULL,
  refresh_token_hash varchar(255) NOT NULL,
  ip varchar(50),
  navegador varchar(150),
  sistema_operacional varchar(150),
  dispositivo varchar(150),
  expira_em timestamp NOT NULL,
  revogado_em timestamp,
  criado_em timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_sessao_usuario FOREIGN KEY (idempresa, idusuario)
    REFERENCES public.usuario(idempresa, idusuario) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT ck_sessao_usuario_expiracao CHECK (expira_em > criado_em),
  CONSTRAINT uq_sessao_usuario_token UNIQUE (refresh_token_hash)
);

CREATE TABLE public.sessao_platform_usuario (
  idsessao_platform integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  idplatform_usuario integer NOT NULL,
  refresh_token_hash varchar(255) NOT NULL,
  ip varchar(50),
  navegador varchar(150),
  sistema_operacional varchar(150),
  dispositivo varchar(150),
  expira_em timestamp NOT NULL,
  revogado_em timestamp,
  criado_em timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_sessao_platform_usuario FOREIGN KEY (idplatform_usuario)
    REFERENCES public.platform_usuario(idplatform_usuario)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT ck_sessao_platform_expiracao CHECK (expira_em > criado_em),
  CONSTRAINT uq_sessao_platform_token UNIQUE (refresh_token_hash)
);

-- =========================================================
-- CADASTROS E PRODUTOS
-- =========================================================

CREATE TABLE public.cliente (
  idcliente integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  idempresa integer NOT NULL,
  tipo_pessoa smallint NOT NULL DEFAULT 1,
  nome varchar(150) NOT NULL,
  documento varchar(18),
  email varchar(150),
  telefone varchar(30),
  cep varchar(20),
  endereco varchar(150),
  numero varchar(20),
  complemento varchar(100),
  bairro varchar(100),
  cidade varchar(100),
  estado varchar(2),
  limite_credito numeric(10,2) NOT NULL DEFAULT 0,
  situacao smallint NOT NULL DEFAULT 1,
  criado_em timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em timestamp,
  CONSTRAINT fk_cliente_empresa FOREIGN KEY (idempresa)
    REFERENCES public.empresa(idempresa) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT ck_cliente_tipo CHECK (tipo_pessoa IN (1, 2)),
  CONSTRAINT ck_cliente_credito CHECK (limite_credito >= 0),
  CONSTRAINT ck_cliente_situacao CHECK (situacao IN (0, 1)),
  CONSTRAINT uq_cliente_empresa_id UNIQUE (idempresa, idcliente),
  CONSTRAINT uq_cliente_empresa_documento UNIQUE (idempresa, documento)
);

CREATE TABLE public.fornecedor (
  idfornecedor integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  idempresa integer NOT NULL,
  razao_social varchar(150) NOT NULL,
  nome_fantasia varchar(150),
  documento varchar(18),
  email varchar(150),
  telefone varchar(30),
  cep varchar(20),
  endereco varchar(150),
  numero varchar(20),
  complemento varchar(100),
  bairro varchar(100),
  cidade varchar(100),
  estado varchar(2),
  situacao smallint NOT NULL DEFAULT 1,
  criado_em timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em timestamp,
  CONSTRAINT fk_fornecedor_empresa FOREIGN KEY (idempresa)
    REFERENCES public.empresa(idempresa) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT ck_fornecedor_situacao CHECK (situacao IN (0, 1)),
  CONSTRAINT uq_fornecedor_empresa_id UNIQUE (idempresa, idfornecedor),
  CONSTRAINT uq_fornecedor_empresa_documento UNIQUE (idempresa, documento)
);

CREATE TABLE public.categoria_produto (
  idcategoria integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  idempresa integer NOT NULL,
  nome varchar(100) NOT NULL,
  descricao varchar(255),
  situacao smallint NOT NULL DEFAULT 1,
  criado_em timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em timestamp,
  CONSTRAINT fk_categoria_empresa FOREIGN KEY (idempresa)
    REFERENCES public.empresa(idempresa) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT ck_categoria_situacao CHECK (situacao IN (0, 1)),
  CONSTRAINT uq_categoria_empresa_id UNIQUE (idempresa, idcategoria),
  CONSTRAINT uq_categoria_empresa_nome UNIQUE (idempresa, nome)
);

CREATE TABLE public.marca (
  idmarca integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  idempresa integer NOT NULL,
  nome varchar(100) NOT NULL,
  situacao smallint NOT NULL DEFAULT 1,
  criado_em timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em timestamp,
  CONSTRAINT fk_marca_empresa FOREIGN KEY (idempresa)
    REFERENCES public.empresa(idempresa) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT ck_marca_situacao CHECK (situacao IN (0, 1)),
  CONSTRAINT uq_marca_empresa_id UNIQUE (idempresa, idmarca),
  CONSTRAINT uq_marca_empresa_nome UNIQUE (idempresa, nome)
);

CREATE TABLE public.produto (
  idproduto integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  idempresa integer NOT NULL,
  idcategoria integer,
  idmarca integer,
  nome varchar(150) NOT NULL,
  sku varchar(80),
  codigo_barras varchar(50),
  descricao text,
  preco_custo numeric(10,2) NOT NULL DEFAULT 0,
  preco_venda numeric(10,2) NOT NULL DEFAULT 0,
  estoque_minimo numeric(10,3) NOT NULL DEFAULT 0,
  estoque_maximo numeric(10,3) NOT NULL DEFAULT 0,
  situacao smallint NOT NULL DEFAULT 1,
  criado_em timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em timestamp,
  CONSTRAINT fk_produto_empresa FOREIGN KEY (idempresa)
    REFERENCES public.empresa(idempresa) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_produto_categoria FOREIGN KEY (idempresa, idcategoria)
    REFERENCES public.categoria_produto(idempresa, idcategoria)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_produto_marca FOREIGN KEY (idempresa, idmarca)
    REFERENCES public.marca(idempresa, idmarca) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT ck_produto_valores CHECK (
    preco_custo >= 0 AND preco_venda >= 0 AND
    estoque_minimo >= 0 AND estoque_maximo >= 0
  ),
  CONSTRAINT ck_produto_situacao CHECK (situacao IN (0, 1)),
  CONSTRAINT uq_produto_empresa_id UNIQUE (idempresa, idproduto),
  CONSTRAINT uq_produto_empresa_sku UNIQUE (idempresa, sku),
  CONSTRAINT uq_produto_empresa_codigo_barras UNIQUE (idempresa, codigo_barras)
);

-- =========================================================
-- ESTOQUE, COMPRAS E VENDAS
-- =========================================================

CREATE TABLE public.estoque (
  idestoque integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  idempresa integer NOT NULL,
  idfilial integer NOT NULL,
  idproduto integer NOT NULL,
  quantidade numeric(10,3) NOT NULL DEFAULT 0,
  situacao smallint NOT NULL DEFAULT 1,
  criado_em timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em timestamp,
  CONSTRAINT fk_estoque_filial FOREIGN KEY (idempresa, idfilial)
    REFERENCES public.filial(idempresa, idfilial) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_estoque_produto FOREIGN KEY (idempresa, idproduto)
    REFERENCES public.produto(idempresa, idproduto) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT ck_estoque_situacao CHECK (situacao IN (0, 1)),
  CONSTRAINT uq_estoque_empresa_filial_produto UNIQUE (idempresa, idfilial, idproduto)
);

CREATE TABLE public.movimentacao_estoque (
  idmovimentacao_estoque integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  idempresa integer NOT NULL,
  idfilial integer NOT NULL,
  idproduto integer NOT NULL,
  idusuario integer,
  tipo smallint NOT NULL,
  quantidade numeric(10,3) NOT NULL,
  documento_referencia varchar(100),
  observacao varchar(500),
  situacao smallint NOT NULL DEFAULT 1,
  criado_em timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em timestamp,
  CONSTRAINT fk_mov_estoque_filial FOREIGN KEY (idempresa, idfilial)
    REFERENCES public.filial(idempresa, idfilial) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_mov_estoque_produto FOREIGN KEY (idempresa, idproduto)
    REFERENCES public.produto(idempresa, idproduto) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_mov_estoque_usuario FOREIGN KEY (idempresa, idusuario)
    REFERENCES public.usuario(idempresa, idusuario) ON UPDATE CASCADE ON DELETE SET NULL (idusuario),
  CONSTRAINT ck_mov_estoque_tipo CHECK (tipo IN (1, 2, 3, 4, 5)),
  CONSTRAINT ck_mov_estoque_quantidade CHECK (quantidade > 0),
  CONSTRAINT ck_mov_estoque_situacao CHECK (situacao IN (0, 1))
);

CREATE TABLE public.compra (
  idcompra integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  idempresa integer NOT NULL,
  idfilial integer NOT NULL,
  idfornecedor integer,
  idusuario integer,
  data_compra timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  valor_total numeric(10,2) NOT NULL DEFAULT 0,
  situacao smallint NOT NULL DEFAULT 1,
  criado_em timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em timestamp,
  CONSTRAINT fk_compra_filial FOREIGN KEY (idempresa, idfilial)
    REFERENCES public.filial(idempresa, idfilial) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_compra_fornecedor FOREIGN KEY (idempresa, idfornecedor)
    REFERENCES public.fornecedor(idempresa, idfornecedor) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_compra_usuario FOREIGN KEY (idempresa, idusuario)
    REFERENCES public.usuario(idempresa, idusuario) ON UPDATE CASCADE ON DELETE SET NULL (idusuario),
  CONSTRAINT ck_compra_valor CHECK (valor_total >= 0),
  CONSTRAINT ck_compra_situacao CHECK (situacao IN (1, 2, 3, 4)),
  CONSTRAINT uq_compra_empresa_id UNIQUE (idempresa, idcompra)
);

CREATE TABLE public.compra_item (
  idcompra_item integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  idempresa integer NOT NULL,
  idfilial integer NOT NULL,
  idcompra integer NOT NULL,
  idproduto integer NOT NULL,
  quantidade numeric(10,3) NOT NULL,
  valor_unitario numeric(10,2) NOT NULL,
  valor_total numeric(10,2) NOT NULL,
  situacao smallint NOT NULL DEFAULT 1,
  criado_em timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em timestamp,
  CONSTRAINT fk_compra_item_compra FOREIGN KEY (idempresa, idcompra)
    REFERENCES public.compra(idempresa, idcompra) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_compra_item_filial FOREIGN KEY (idempresa, idfilial)
    REFERENCES public.filial(idempresa, idfilial) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_compra_item_produto FOREIGN KEY (idempresa, idproduto)
    REFERENCES public.produto(idempresa, idproduto) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT ck_compra_item_valores CHECK (
    quantidade > 0 AND valor_unitario >= 0 AND valor_total >= 0
  ),
  CONSTRAINT ck_compra_item_situacao CHECK (situacao IN (0, 1))
);

CREATE TABLE public.venda (
  idvenda integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  idempresa integer NOT NULL,
  idfilial integer NOT NULL,
  idcliente integer,
  idusuario integer,
  data_venda timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  valor_bruto numeric(10,2) NOT NULL DEFAULT 0,
  valor_desconto numeric(10,2) NOT NULL DEFAULT 0,
  valor_total numeric(10,2) NOT NULL DEFAULT 0,
  situacao smallint NOT NULL DEFAULT 1,
  criado_em timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em timestamp,
  CONSTRAINT fk_venda_filial FOREIGN KEY (idempresa, idfilial)
    REFERENCES public.filial(idempresa, idfilial) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_venda_cliente FOREIGN KEY (idempresa, idcliente)
    REFERENCES public.cliente(idempresa, idcliente) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_venda_usuario FOREIGN KEY (idempresa, idusuario)
    REFERENCES public.usuario(idempresa, idusuario) ON UPDATE CASCADE ON DELETE SET NULL (idusuario),
  CONSTRAINT ck_venda_valores CHECK (
    valor_bruto >= 0 AND valor_desconto >= 0 AND valor_total >= 0
  ),
  CONSTRAINT ck_venda_situacao CHECK (situacao IN (1, 2, 3, 4)),
  CONSTRAINT uq_venda_empresa_id UNIQUE (idempresa, idvenda)
);

CREATE TABLE public.venda_item (
  idvenda_item integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  idempresa integer NOT NULL,
  idfilial integer NOT NULL,
  idvenda integer NOT NULL,
  idproduto integer NOT NULL,
  quantidade numeric(10,3) NOT NULL,
  valor_unitario numeric(10,2) NOT NULL,
  valor_desconto numeric(10,2) NOT NULL DEFAULT 0,
  valor_total numeric(10,2) NOT NULL,
  situacao smallint NOT NULL DEFAULT 1,
  criado_em timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em timestamp,
  CONSTRAINT fk_venda_item_venda FOREIGN KEY (idempresa, idvenda)
    REFERENCES public.venda(idempresa, idvenda) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_venda_item_filial FOREIGN KEY (idempresa, idfilial)
    REFERENCES public.filial(idempresa, idfilial) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_venda_item_produto FOREIGN KEY (idempresa, idproduto)
    REFERENCES public.produto(idempresa, idproduto) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT ck_venda_item_valores CHECK (
    quantidade > 0 AND valor_unitario >= 0 AND valor_desconto >= 0 AND valor_total >= 0
  ),
  CONSTRAINT ck_venda_item_situacao CHECK (situacao IN (0, 1))
);

-- =========================================================
-- FINANCEIRO, TAREFAS E NOTIFICACOES
-- =========================================================

CREATE TABLE public.conta_pagar (
  idconta_pagar integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  idempresa integer NOT NULL,
  idfilial integer,
  idfornecedor integer,
  idcompra integer,
  descricao varchar(255) NOT NULL,
  valor numeric(10,2) NOT NULL,
  data_vencimento date NOT NULL,
  data_pagamento date,
  situacao smallint NOT NULL DEFAULT 1,
  criado_em timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em timestamp,
  CONSTRAINT fk_conta_pagar_empresa FOREIGN KEY (idempresa)
    REFERENCES public.empresa(idempresa) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_conta_pagar_filial FOREIGN KEY (idempresa, idfilial)
    REFERENCES public.filial(idempresa, idfilial) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_conta_pagar_fornecedor FOREIGN KEY (idempresa, idfornecedor)
    REFERENCES public.fornecedor(idempresa, idfornecedor) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_conta_pagar_compra FOREIGN KEY (idempresa, idcompra)
    REFERENCES public.compra(idempresa, idcompra) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT ck_conta_pagar_valor CHECK (valor > 0),
  CONSTRAINT ck_conta_pagar_situacao CHECK (situacao IN (1, 2, 3))
);

CREATE TABLE public.conta_receber (
  idconta_receber integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  idempresa integer NOT NULL,
  idfilial integer,
  idcliente integer,
  idvenda integer,
  descricao varchar(255) NOT NULL,
  valor numeric(10,2) NOT NULL,
  data_vencimento date NOT NULL,
  data_recebimento date,
  situacao smallint NOT NULL DEFAULT 1,
  criado_em timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em timestamp,
  CONSTRAINT fk_conta_receber_empresa FOREIGN KEY (idempresa)
    REFERENCES public.empresa(idempresa) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_conta_receber_filial FOREIGN KEY (idempresa, idfilial)
    REFERENCES public.filial(idempresa, idfilial) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_conta_receber_cliente FOREIGN KEY (idempresa, idcliente)
    REFERENCES public.cliente(idempresa, idcliente) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_conta_receber_venda FOREIGN KEY (idempresa, idvenda)
    REFERENCES public.venda(idempresa, idvenda) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT ck_conta_receber_valor CHECK (valor > 0),
  CONSTRAINT ck_conta_receber_situacao CHECK (situacao IN (1, 2, 3))
);

CREATE TABLE public.caixa (
  idcaixa integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  idempresa integer NOT NULL,
  idfilial integer NOT NULL,
  idusuario_abertura integer NOT NULL,
  aberto_em timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  fechado_em timestamp,
  saldo_inicial numeric(10,2) NOT NULL DEFAULT 0,
  saldo_final numeric(10,2),
  situacao smallint NOT NULL DEFAULT 1,
  criado_em timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em timestamp,
  CONSTRAINT fk_caixa_filial FOREIGN KEY (idempresa, idfilial)
    REFERENCES public.filial(idempresa, idfilial) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_caixa_usuario FOREIGN KEY (idempresa, idusuario_abertura)
    REFERENCES public.usuario(idempresa, idusuario) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT ck_caixa_saldos CHECK (saldo_inicial >= 0 AND (saldo_final IS NULL OR saldo_final >= 0)),
  CONSTRAINT ck_caixa_datas CHECK (fechado_em IS NULL OR fechado_em >= aberto_em),
  CONSTRAINT ck_caixa_situacao CHECK (situacao IN (1, 2)),
  CONSTRAINT uq_caixa_empresa_id UNIQUE (idempresa, idcaixa)
);

CREATE TABLE public.movimentacao_caixa (
  idmovimentacao_caixa integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  idempresa integer NOT NULL,
  idfilial integer NOT NULL,
  idcaixa integer NOT NULL,
  idusuario integer,
  tipo smallint NOT NULL,
  descricao varchar(255) NOT NULL,
  valor numeric(10,2) NOT NULL,
  situacao smallint NOT NULL DEFAULT 1,
  criado_em timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em timestamp,
  CONSTRAINT fk_mov_caixa_caixa FOREIGN KEY (idempresa, idcaixa)
    REFERENCES public.caixa(idempresa, idcaixa) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_mov_caixa_filial FOREIGN KEY (idempresa, idfilial)
    REFERENCES public.filial(idempresa, idfilial) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_mov_caixa_usuario FOREIGN KEY (idempresa, idusuario)
    REFERENCES public.usuario(idempresa, idusuario) ON UPDATE CASCADE ON DELETE SET NULL (idusuario),
  CONSTRAINT ck_mov_caixa_tipo CHECK (tipo IN (1, 2, 3, 4)),
  CONSTRAINT ck_mov_caixa_valor CHECK (valor > 0),
  CONSTRAINT ck_mov_caixa_situacao CHECK (situacao IN (0, 1))
);

CREATE TABLE public.tarefa (
  idtarefa integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  idempresa integer NOT NULL,
  idfilial integer,
  idusuario integer,
  titulo varchar(150) NOT NULL,
  descricao text,
  data_limite timestamp,
  prioridade smallint NOT NULL DEFAULT 2,
  situacao smallint NOT NULL DEFAULT 1,
  criado_em timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em timestamp,
  CONSTRAINT fk_tarefa_empresa FOREIGN KEY (idempresa)
    REFERENCES public.empresa(idempresa) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_tarefa_filial FOREIGN KEY (idempresa, idfilial)
    REFERENCES public.filial(idempresa, idfilial) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_tarefa_usuario FOREIGN KEY (idempresa, idusuario)
    REFERENCES public.usuario(idempresa, idusuario) ON UPDATE CASCADE ON DELETE SET NULL (idusuario),
  CONSTRAINT ck_tarefa_prioridade CHECK (prioridade IN (1, 2, 3)),
  CONSTRAINT ck_tarefa_situacao CHECK (situacao IN (1, 2, 3))
);

CREATE TABLE public.notificacao (
  idnotificacao integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  idempresa integer NOT NULL,
  idfilial integer,
  idusuario integer NOT NULL,
  titulo varchar(150) NOT NULL,
  mensagem text NOT NULL,
  tipo varchar(50),
  link varchar(500),
  lida_em timestamp,
  situacao smallint NOT NULL DEFAULT 1,
  criado_em timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em timestamp,
  CONSTRAINT fk_notificacao_empresa FOREIGN KEY (idempresa)
    REFERENCES public.empresa(idempresa) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_notificacao_filial FOREIGN KEY (idempresa, idfilial)
    REFERENCES public.filial(idempresa, idfilial) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_notificacao_usuario FOREIGN KEY (idempresa, idusuario)
    REFERENCES public.usuario(idempresa, idusuario) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT ck_notificacao_situacao CHECK (situacao IN (0, 1))
);

-- =========================================================
-- AUDITORIA
-- =========================================================

CREATE TABLE public.auditoria (
  idauditoria integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  idempresa integer,
  idfilial integer,
  idusuario integer,
  idplatform_usuario integer,
  origem_usuario varchar(20) NOT NULL,
  tabela varchar(100) NOT NULL,
  registro_id integer,
  acao varchar(50) NOT NULL,
  valores_anteriores jsonb,
  valores_novos jsonb,
  ip varchar(50),
  cidade varchar(100),
  navegador varchar(150),
  sistema_operacional varchar(150),
  dispositivo varchar(150),
  sessao_id varchar(100),
  criado_em timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_auditoria_empresa FOREIGN KEY (idempresa)
    REFERENCES public.empresa(idempresa) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT fk_auditoria_filial FOREIGN KEY (idempresa, idfilial)
    REFERENCES public.filial(idempresa, idfilial) ON UPDATE CASCADE ON DELETE SET NULL (idempresa, idfilial),
  CONSTRAINT fk_auditoria_usuario FOREIGN KEY (idempresa, idusuario)
    REFERENCES public.usuario(idempresa, idusuario) ON UPDATE CASCADE ON DELETE SET NULL (idempresa, idusuario),
  CONSTRAINT fk_auditoria_platform FOREIGN KEY (idplatform_usuario)
    REFERENCES public.platform_usuario(idplatform_usuario) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT ck_auditoria_origem CHECK (origem_usuario IN ('platform', 'empresa', 'sistema')),
  CONSTRAINT ck_auditoria_autor CHECK (
    (origem_usuario = 'platform' AND idplatform_usuario IS NOT NULL AND idusuario IS NULL) OR
    (origem_usuario = 'empresa' AND idusuario IS NOT NULL AND idplatform_usuario IS NULL) OR
    (origem_usuario = 'sistema' AND idusuario IS NULL AND idplatform_usuario IS NULL)
  )
);

-- =========================================================
-- INDICES DE CONSULTA
-- =========================================================

CREATE INDEX idx_assinatura_empresa_status ON public.assinatura(idempresa, status);
CREATE INDEX idx_filial_empresa_situacao ON public.filial(idempresa, situacao);
CREATE INDEX idx_usuario_empresa_situacao ON public.usuario(idempresa, situacao);
CREATE INDEX idx_usuario_filial_padrao ON public.usuario(idempresa, idfilial_padrao);
CREATE INDEX idx_funcionario_empresa_filial ON public.funcionario(idempresa, idfilial);
CREATE INDEX idx_funcionario_cargo ON public.funcionario(idempresa, idcargo);
CREATE INDEX idx_sessao_usuario_ativa ON public.sessao_usuario(idempresa, idusuario, expira_em)
  WHERE revogado_em IS NULL;
CREATE INDEX idx_cliente_empresa_situacao ON public.cliente(idempresa, situacao);
CREATE INDEX idx_fornecedor_empresa_situacao ON public.fornecedor(idempresa, situacao);
CREATE INDEX idx_produto_empresa_situacao ON public.produto(idempresa, situacao);
CREATE INDEX idx_estoque_empresa_filial ON public.estoque(idempresa, idfilial);
CREATE INDEX idx_estoque_produto ON public.estoque(idempresa, idproduto);
CREATE INDEX idx_mov_estoque_empresa_filial_data
  ON public.movimentacao_estoque(idempresa, idfilial, criado_em);
CREATE INDEX idx_mov_estoque_produto ON public.movimentacao_estoque(idempresa, idproduto);
CREATE INDEX idx_compra_empresa_filial_data ON public.compra(idempresa, idfilial, data_compra);
CREATE INDEX idx_compra_fornecedor ON public.compra(idempresa, idfornecedor);
CREATE INDEX idx_compra_item_compra ON public.compra_item(idempresa, idcompra);
CREATE INDEX idx_compra_item_produto ON public.compra_item(idempresa, idproduto);
CREATE INDEX idx_venda_empresa_filial_data ON public.venda(idempresa, idfilial, data_venda);
CREATE INDEX idx_venda_cliente ON public.venda(idempresa, idcliente);
CREATE INDEX idx_venda_item_venda ON public.venda_item(idempresa, idvenda);
CREATE INDEX idx_venda_item_produto ON public.venda_item(idempresa, idproduto);
CREATE INDEX idx_conta_pagar_vencimento
  ON public.conta_pagar(idempresa, data_vencimento, situacao);
CREATE INDEX idx_conta_pagar_fornecedor ON public.conta_pagar(idempresa, idfornecedor);
CREATE INDEX idx_conta_receber_vencimento
  ON public.conta_receber(idempresa, data_vencimento, situacao);
CREATE INDEX idx_conta_receber_cliente ON public.conta_receber(idempresa, idcliente);
CREATE INDEX idx_caixa_empresa_filial ON public.caixa(idempresa, idfilial, situacao);
CREATE INDEX idx_mov_caixa_caixa ON public.movimentacao_caixa(idempresa, idcaixa, criado_em);
CREATE INDEX idx_notificacao_usuario ON public.notificacao(idempresa, idusuario, lida_em);
CREATE INDEX idx_auditoria_empresa_data ON public.auditoria(idempresa, criado_em);
CREATE INDEX idx_auditoria_filial_data ON public.auditoria(idempresa, idfilial, criado_em);
CREATE INDEX idx_auditoria_usuario ON public.auditoria(idempresa, idusuario);
CREATE INDEX idx_auditoria_registro ON public.auditoria(tabela, registro_id);

-- Permissoes globais iniciais. Perfis e vinculos continuam por empresa.
INSERT INTO public.permissao (modulo, acao, descricao) VALUES
  ('empresa', 'visualizar', 'Visualizar dados da empresa'),
  ('empresa', 'editar', 'Editar dados da empresa'),
  ('filial', 'criar', 'Criar filiais'),
  ('filial', 'editar', 'Editar filiais'),
  ('usuario', 'criar', 'Criar usuarios'),
  ('usuario', 'editar', 'Editar usuarios'),
  ('funcionario', 'criar', 'Criar funcionarios'),
  ('funcionario', 'editar', 'Editar funcionarios'),
  ('cliente', 'criar', 'Criar clientes'),
  ('cliente', 'editar', 'Editar clientes'),
  ('produto', 'criar', 'Criar produtos'),
  ('produto', 'editar', 'Editar produtos'),
  ('estoque', 'visualizar', 'Visualizar estoque'),
  ('estoque', 'movimentar', 'Movimentar estoque'),
  ('venda', 'criar', 'Criar vendas'),
  ('venda', 'cancelar', 'Cancelar vendas'),
  ('financeiro', 'visualizar', 'Visualizar financeiro'),
  ('financeiro', 'editar', 'Editar financeiro'),
  ('relatorio', 'visualizar', 'Visualizar relatorios'),
  ('configuracao', 'editar', 'Editar configuracoes');

COMMENT ON TABLE public.platform_usuario IS 'Usuarios internos da NovaWave Tech, separados dos tenants.';
COMMENT ON TABLE public.usuario IS 'Usuarios das empresas clientes com acesso ao ERP.';
COMMENT ON TABLE public.funcionario IS 'Vinculos profissionais; nao implica acesso ao sistema.';
COMMENT ON COLUMN public.perfil_acesso.escopo IS '1=empresa, 2=filial';
COMMENT ON COLUMN public.assinatura.status IS '1=ativa, 2=em_teste, 3=vencida, 4=cancelada, 5=bloqueada';
COMMENT ON COLUMN public.empresa.situacao IS '0=inativa, 1=ativa, 2=bloqueada';

COMMIT;
