export const platformTokens = {
  colors: {
    canvas: 'var(--chakra-colors-erp-canvas)',
    surface: 'var(--chakra-colors-erp-surface)',
    surfaceSubtle: 'var(--chakra-colors-erp-surface-subtle)',
    surfaceHover: 'var(--chakra-colors-erp-hover)',
    border: 'var(--chakra-colors-erp-border)',
    borderStrong: 'var(--chakra-colors-erp-border-strong)',
    text: 'var(--chakra-colors-erp-text)',
    textSecondary: 'var(--chakra-colors-erp-text-secondary)',
    muted: 'var(--chakra-colors-erp-text-muted)',
    primary: '#2563FF',
    primaryLight: '#2F80FF',
    primaryHover: '#1D4ED8',
    primarySubtle: 'var(--chakra-colors-erp-hover)',
    indigo: '#4F46E5',
    purple: '#8B5CF6',
    brandLight: '#84B8FF',
    sidebar: 'var(--chakra-colors-erp-sidebar)',
    sidebarHover: 'var(--chakra-colors-erp-hover)',
    sidebarText: 'var(--chakra-colors-erp-text-secondary)',
    sidebarTextStrong: 'var(--chakra-colors-erp-text)',
    sidebarMuted: 'var(--chakra-colors-erp-text-muted)',
    placeholder: 'var(--chakra-colors-erp-text-muted)',
    success: 'var(--chakra-colors-erp-success)',
    successSubtle: 'var(--chakra-colors-erp-hover)',
    warning: 'var(--chakra-colors-erp-warning)',
    warningSubtle: 'var(--chakra-colors-erp-hover)',
    danger: 'var(--chakra-colors-erp-danger)',
    dangerSubtle: 'var(--chakra-colors-erp-hover)',
    dangerBorder: 'var(--chakra-colors-erp-border-strong)',
    dangerTextHover: '#FF9DA4',
    neutralSubtle: 'var(--chakra-colors-erp-hover)',
    borderSubtle: 'var(--chakra-colors-erp-border)',
    loginCanvas: 'var(--chakra-colors-erp-canvas)',
  },
  radii: { control: '8px', surface: '12px' },
  shadows: {
    surface: '0 1px 2px rgba(16,24,40,.04)',
    floating: '0 16px 40px rgba(16,24,40,.14)',
    focus: '0 0 0 3px rgba(37,99,255,.14)',
  },
  transition: '160ms ease',
} as const;
