<?php

namespace App\Modules\Products\Repositories;

use App\Infrastructures\Config\Database;
use InvalidArgumentException;
use PDO;
use Throwable;

final class ProductRepository
{
    private PDO $pdo;
    public function __construct(){ $this->pdo=Database::getInstance(); }

    public function index(int $companyId,array $filters): array
    {
        $where=['p.idempresa=:company_id'];$params=['company_id'=>$companyId];
        foreach(['p.idcategoria'=>'category','p.idmarca'=>'brand','p.situacao'=>'status'] as $column=>$key)if(($filters[$key]??'')!==''){$where[]="$column=:$key";$params[$key]=(int)$filters[$key];}
        if(!empty($filters['q'])){$where[]='(p.nome ILIKE :q OR p.sku ILIKE :q OR p.codigo_barras ILIKE :q OR m.nome ILIKE :q OR c.nome ILIKE :q)';$params['q']='%'.trim($filters['q']).'%';}
        if(($filters['supplier']??'')!==''){$where[]='EXISTS(SELECT 1 FROM produto_fornecedor pfx WHERE pfx.idempresa=p.idempresa AND pfx.idproduto=p.idproduto AND pfx.idfornecedor=:supplier)';$params['supplier']=(int)$filters['supplier'];}
        if(($filters['branch']??'')!==''){$where[]='EXISTS(SELECT 1 FROM estoque ex WHERE ex.idempresa=p.idempresa AND ex.idproduto=p.idproduto AND ex.idfilial=:branch)';$params['branch']=(int)$filters['branch'];}
        if(($filters['stock']??'')==='with')$where[]='COALESCE(es.stock,0)>0';if(($filters['stock']??'')==='without')$where[]='COALESCE(es.stock,0)=0';if(($filters['stock']??'')==='critical')$where[]='COALESCE(es.stock,0)<=p.estoque_minimo';
        if(($filters['price']??'')==='low')$where[]='p.preco_venda<100';if(($filters['price']??'')==='high')$where[]='p.preco_venda>=100';
        $order=($filters['best_sellers']??'')==='1'?'COALESCE(v.sold,0) DESC,p.nome':'p.nome';
        $products=$this->all("SELECT p.*,c.nome categoria,m.nome marca,pi.url imagem,COALESCE(es.stock,0) estoque,COALESCE(es.reserved,0) reservado,COALESCE(es.branches,0) filiais_estoque,COALESCE(v.sold,0) vendido,COALESCE(v.revenue,0) receita,v.last_sale,CASE WHEN p.preco_venda>0 THEN ROUND(((p.preco_venda-p.preco_custo)/p.preco_venda)*100,2) ELSE 0 END margem FROM produto p LEFT JOIN categoria_produto c ON c.idempresa=p.idempresa AND c.idcategoria=p.idcategoria LEFT JOIN marca m ON m.idempresa=p.idempresa AND m.idmarca=p.idmarca LEFT JOIN produto_imagem pi ON pi.idempresa=p.idempresa AND pi.idproduto=p.idproduto AND pi.principal=true LEFT JOIN (SELECT idempresa,idproduto,SUM(quantidade) stock,SUM(quantidade_reservada) reserved,COUNT(*) FILTER(WHERE quantidade>0) branches FROM estoque GROUP BY idempresa,idproduto) es ON es.idempresa=p.idempresa AND es.idproduto=p.idproduto LEFT JOIN (SELECT vi.idempresa,vi.idproduto,SUM(vi.quantidade) FILTER(WHERE vi.situacao=1 AND v.situacao=1) sold,SUM(vi.valor_total) FILTER(WHERE vi.situacao=1 AND v.situacao=1) revenue,MAX(v.data_venda) FILTER(WHERE vi.situacao=1 AND v.situacao=1) last_sale FROM venda_item vi JOIN venda v ON v.idempresa=vi.idempresa AND v.idvenda=vi.idvenda GROUP BY vi.idempresa,vi.idproduto) v ON v.idempresa=p.idempresa AND v.idproduto=p.idproduto WHERE ".implode(' AND ',$where)." ORDER BY $order",$params);
        $metrics=$this->one("SELECT COUNT(*) total,COUNT(*) FILTER(WHERE situacao=1) active,COUNT(*) FILTER(WHERE situacao=0) inactive FROM produto WHERE idempresa=:company_id",['company_id'=>$companyId]);
        $stock=$this->one("SELECT COUNT(DISTINCT e.idproduto) FILTER(WHERE e.quantidade<=p.estoque_minimo) critical,COUNT(DISTINCT e.idfilial) FILTER(WHERE e.quantidade>0) branches,COALESCE(SUM(e.quantidade*p.preco_custo),0) stock_value FROM estoque e JOIN produto p ON p.idempresa=e.idempresa AND p.idproduto=e.idproduto WHERE e.idempresa=:company_id",['company_id'=>$companyId]);
        $best=$this->one("SELECT p.nome FROM venda_item vi JOIN venda v ON v.idempresa=vi.idempresa AND v.idvenda=vi.idvenda JOIN produto p ON p.idempresa=vi.idempresa AND p.idproduto=vi.idproduto WHERE vi.idempresa=:company_id AND vi.situacao=1 AND v.situacao=1 GROUP BY p.idproduto ORDER BY SUM(vi.quantidade) DESC LIMIT 1",['company_id'=>$companyId]);
        return ['products'=>$products,'metrics'=>array_merge($metrics,$stock,['best_seller'=>$best['nome']??'-']),'options'=>$this->options($companyId)];
    }

    public function show(int $companyId,int $productId): ?array
    {
        $product=$this->one("SELECT p.*,c.nome categoria,m.nome marca,CASE WHEN p.preco_venda>0 THEN ROUND(((p.preco_venda-p.preco_custo)/p.preco_venda)*100,2) ELSE 0 END margem FROM produto p LEFT JOIN categoria_produto c ON c.idempresa=p.idempresa AND c.idcategoria=p.idcategoria LEFT JOIN marca m ON m.idempresa=p.idempresa AND m.idmarca=p.idmarca WHERE p.idempresa=:company_id AND p.idproduto=:product_id",['company_id'=>$companyId,'product_id'=>$productId]);if(!$product)return null;
        $product['images']=$this->all('SELECT idproduto_imagem,url,principal,ordem FROM produto_imagem WHERE idempresa=:company_id AND idproduto=:product_id ORDER BY principal DESC,ordem',['company_id'=>$companyId,'product_id'=>$productId]);
        $product['suppliers']=$this->all('SELECT pf.idfornecedor,pf.principal,pf.codigo_fornecedor,pf.ultimo_preco,f.razao_social,f.nome_fantasia FROM produto_fornecedor pf JOIN fornecedor f ON f.idempresa=pf.idempresa AND f.idfornecedor=pf.idfornecedor WHERE pf.idempresa=:company_id AND pf.idproduto=:product_id ORDER BY pf.principal DESC,f.razao_social',['company_id'=>$companyId,'product_id'=>$productId]);
        $product['stock']=$this->all('SELECT e.idfilial,f.nome filial,e.quantidade,e.quantidade_reservada,(e.quantidade-e.quantidade_reservada) disponivel,(SELECT MAX(me.criado_em) FROM movimentacao_estoque me WHERE me.idempresa=e.idempresa AND me.idfilial=e.idfilial AND me.idproduto=e.idproduto) ultima_movimentacao FROM estoque e JOIN filial f ON f.idempresa=e.idempresa AND f.idfilial=e.idfilial WHERE e.idempresa=:company_id AND e.idproduto=:product_id ORDER BY f.matriz DESC,f.nome',['company_id'=>$companyId,'product_id'=>$productId]);
        $product['movements']=$this->all('SELECT me.idmovimentacao_estoque,me.tipo,me.quantidade,me.documento_referencia,me.observacao,me.criado_em,f.nome filial,u.nome usuario FROM movimentacao_estoque me JOIN filial f ON f.idempresa=me.idempresa AND f.idfilial=me.idfilial LEFT JOIN usuario u ON u.idempresa=me.idempresa AND u.idusuario=me.idusuario WHERE me.idempresa=:company_id AND me.idproduto=:product_id ORDER BY me.criado_em DESC LIMIT 40',['company_id'=>$companyId,'product_id'=>$productId]);
        $product['sales']=$this->one("SELECT COALESCE(SUM(vi.quantidade) FILTER(WHERE vi.situacao=1 AND v.situacao=1),0) quantity,COALESCE(SUM(vi.valor_total) FILTER(WHERE vi.situacao=1 AND v.situacao=1),0) revenue,COALESCE(AVG(vi.valor_total) FILTER(WHERE vi.situacao=1 AND v.situacao=1),0) average_ticket,MAX(v.data_venda) FILTER(WHERE vi.situacao=1 AND v.situacao=1) last_sale FROM venda_item vi JOIN venda v ON v.idempresa=vi.idempresa AND v.idvenda=vi.idvenda WHERE vi.idempresa=:company_id AND vi.idproduto=:product_id",['company_id'=>$companyId,'product_id'=>$productId]);
        $product['top_branches']=$this->all("SELECT f.nome filial,SUM(vi.quantidade) quantity,SUM(vi.valor_total) revenue FROM venda_item vi JOIN venda v ON v.idempresa=vi.idempresa AND v.idvenda=vi.idvenda JOIN filial f ON f.idempresa=vi.idempresa AND f.idfilial=vi.idfilial WHERE vi.idempresa=:company_id AND vi.idproduto=:product_id AND vi.situacao=1 AND v.situacao=1 GROUP BY f.idfilial ORDER BY quantity DESC LIMIT 5",['company_id'=>$companyId,'product_id'=>$productId]);
        $product['last_purchase']=$this->one('SELECT c.data_compra,ci.valor_unitario,f.razao_social fornecedor FROM compra_item ci JOIN compra c ON c.idempresa=ci.idempresa AND c.idcompra=ci.idcompra LEFT JOIN fornecedor f ON f.idempresa=c.idempresa AND f.idfornecedor=c.idfornecedor WHERE ci.idempresa=:company_id AND ci.idproduto=:product_id AND ci.situacao=1 ORDER BY c.data_compra DESC LIMIT 1',['company_id'=>$companyId,'product_id'=>$productId]);
        $product['history']=$this->all("SELECT idauditoria,acao,valores_anteriores,valores_novos,criado_em FROM auditoria WHERE idempresa=:company_id AND ((tabela='produto' AND registro_id=:product_id) OR (tabela='estoque' AND registro_id=:product_id)) ORDER BY criado_em DESC LIMIT 40",['company_id'=>$companyId,'product_id'=>$productId]);
        return $product;
    }

    public function create(int $companyId,int $actorId,array $data,?string $ip,?string $agent): int
    {
        return $this->transaction(function()use($companyId,$actorId,$data,$ip,$agent){$this->assertReferences($companyId,$data);$s=$this->pdo->prepare('INSERT INTO produto(idempresa,idcategoria,idmarca,nome,sku,codigo_barras,descricao,unidade,preco_custo,preco_venda,preco_promocional,estoque_minimo,estoque_maximo,peso,altura,largura,comprimento,ncm,cest,cfop,origem,tributacao,garantia_meses,permite_estoque_negativo,lancamento,destaque,situacao) VALUES(:company_id,:category,:brand,:name,:sku,:barcode,:description,:unit,:cost,:price,:promo,:stock_min,:stock_max,:weight,:height,:width,:length,:ncm,:cest,:cfop,:origin,:taxation,:warranty,:negative_stock,:launch,:featured,:status) RETURNING idproduto');$s->execute($this->params($companyId,$data));$id=(int)$s->fetchColumn();$this->syncRelations($companyId,$id,$data);$this->initialStock($companyId,$actorId,$id,$data);$this->audit($companyId,$actorId,$id,'criar',null,['nome'=>$data['nome']],$ip,$agent);return $id;});
    }

    public function update(int $companyId,int $actorId,int $productId,array $data,?string $ip,?string $agent): void
    {
        $this->transaction(function()use($companyId,$actorId,$productId,$data,$ip,$agent){$before=$this->one('SELECT nome,preco_custo,preco_venda FROM produto WHERE idempresa=:company_id AND idproduto=:product_id',['company_id'=>$companyId,'product_id'=>$productId]);if(!$before)throw new InvalidArgumentException('Produto nao encontrado');$this->assertReferences($companyId,$data);$params=$this->params($companyId,$data);$params['product_id']=$productId;$this->pdo->prepare('UPDATE produto SET idcategoria=:category,idmarca=:brand,nome=:name,sku=:sku,codigo_barras=:barcode,descricao=:description,unidade=:unit,preco_custo=:cost,preco_venda=:price,preco_promocional=:promo,estoque_minimo=:stock_min,estoque_maximo=:stock_max,peso=:weight,altura=:height,largura=:width,comprimento=:length,ncm=:ncm,cest=:cest,cfop=:cfop,origem=:origin,tributacao=:taxation,garantia_meses=:warranty,permite_estoque_negativo=:negative_stock,lancamento=:launch,destaque=:featured,situacao=:status,ultimo_reajuste=CASE WHEN preco_custo<>:cost OR preco_venda<>:price THEN CURRENT_TIMESTAMP ELSE ultimo_reajuste END,atualizado_em=CURRENT_TIMESTAMP WHERE idempresa=:company_id AND idproduto=:product_id')->execute($params);$this->syncRelations($companyId,$productId,$data);$this->audit($companyId,$actorId,$productId,'editar',$before,['nome'=>$data['nome'],'preco_venda'=>$data['preco_venda']],$ip,$agent);});
    }

    public function setStatus(int $companyId,int $actorId,int $productId,int $status,?string $ip,?string $agent): void { $s=$this->pdo->prepare('UPDATE produto SET situacao=:status,atualizado_em=CURRENT_TIMESTAMP WHERE idempresa=:company_id AND idproduto=:product_id');$s->execute(['status'=>$status,'company_id'=>$companyId,'product_id'=>$productId]);if(!$s->rowCount())throw new InvalidArgumentException('Produto nao encontrado');$this->audit($companyId,$actorId,$productId,$status?'ativar':'inativar',null,['situacao'=>$status],$ip,$agent); }

    public function duplicate(int $companyId,int $actorId,int $productId,?string $ip,?string $agent): int
    {
        return $this->transaction(function()use($companyId,$actorId,$productId,$ip,$agent){$p=$this->one('SELECT * FROM produto WHERE idempresa=:company_id AND idproduto=:product_id',['company_id'=>$companyId,'product_id'=>$productId]);if(!$p)throw new InvalidArgumentException('Produto nao encontrado');$sku=($p['sku']?:'PROD-'.$productId).'-COPIA-'.time();$s=$this->pdo->prepare('INSERT INTO produto(idempresa,idcategoria,idmarca,nome,sku,descricao,unidade,preco_custo,preco_venda,preco_promocional,estoque_minimo,estoque_maximo,peso,altura,largura,comprimento,ncm,cest,cfop,origem,tributacao,garantia_meses,permite_estoque_negativo,lancamento,destaque,situacao) SELECT idempresa,idcategoria,idmarca,nome||\' - Copia\',:sku,descricao,unidade,preco_custo,preco_venda,preco_promocional,estoque_minimo,estoque_maximo,peso,altura,largura,comprimento,ncm,cest,cfop,origem,tributacao,garantia_meses,permite_estoque_negativo,false,false,1 FROM produto WHERE idempresa=:company_id AND idproduto=:product_id RETURNING idproduto');$s->execute(['sku'=>$sku,'company_id'=>$companyId,'product_id'=>$productId]);$id=(int)$s->fetchColumn();$this->audit($companyId,$actorId,$id,'duplicar',null,['origem'=>$productId],$ip,$agent);return $id;});
    }

    public function moveStock(int $companyId,int $actorId,int $productId,array $data,?string $ip,?string $agent): void
    {
        $this->transaction(function()use($companyId,$actorId,$productId,$data,$ip,$agent){$product=$this->one('SELECT permite_estoque_negativo FROM produto WHERE idempresa=:company_id AND idproduto=:product_id',['company_id'=>$companyId,'product_id'=>$productId]);if(!$product)throw new InvalidArgumentException('Produto nao encontrado');$branch=$this->one('SELECT permite_estoque_negativo FROM filial WHERE idempresa=:company_id AND idfilial=:branch_id AND situacao=1',['company_id'=>$companyId,'branch_id'=>(int)$data['idfilial']]);if(!$branch)throw new InvalidArgumentException('Filial invalida');$quantity=(float)$data['quantidade'];$type=(int)$data['tipo'];$current=$this->one('SELECT quantidade FROM estoque WHERE idempresa=:company_id AND idfilial=:branch_id AND idproduto=:product_id FOR UPDATE',['company_id'=>$companyId,'branch_id'=>(int)$data['idfilial'],'product_id'=>$productId]);$before=(float)($current['quantidade']??0);$after=$type===1?$before+$quantity:($type===2?$before-$quantity:$quantity);if($after<0&&!$product['permite_estoque_negativo']&&!$branch['permite_estoque_negativo'])throw new InvalidArgumentException('Estoque insuficiente para a saida');$this->pdo->prepare('INSERT INTO estoque(idempresa,idfilial,idproduto,quantidade,situacao) VALUES(:company_id,:branch_id,:product_id,:quantity,1) ON CONFLICT(idempresa,idfilial,idproduto) DO UPDATE SET quantidade=EXCLUDED.quantidade,atualizado_em=CURRENT_TIMESTAMP')->execute(['company_id'=>$companyId,'branch_id'=>(int)$data['idfilial'],'product_id'=>$productId,'quantity'=>$after]);$this->pdo->prepare('INSERT INTO movimentacao_estoque(idempresa,idfilial,idproduto,idusuario,tipo,quantidade,documento_referencia,observacao,situacao) VALUES(:company_id,:branch_id,:product_id,:actor_id,:type,:quantity,:document,:note,1)')->execute(['company_id'=>$companyId,'branch_id'=>(int)$data['idfilial'],'product_id'=>$productId,'actor_id'=>$actorId,'type'=>$type,'quantity'=>$quantity,'document'=>$data['documento_referencia']??null,'note'=>$data['observacao']??null]);$this->audit($companyId,$actorId,$productId,'movimentar_estoque',['quantidade'=>$before],['quantidade'=>$after,'filial'=>$data['idfilial']],$ip,$agent);});
    }

    private function params(int $companyId,array $data): array { $n=fn(string $key)=>(isset($data[$key])&&$data[$key]!=='')?$data[$key]:null;return ['company_id'=>$companyId,'category'=>(int)$data['idcategoria'],'brand'=>!empty($data['idmarca'])?(int)$data['idmarca']:null,'name'=>trim($data['nome']),'sku'=>$n('sku'),'barcode'=>$n('codigo_barras'),'description'=>$n('descricao'),'unit'=>$data['unidade']??'UN','cost'=>(float)($data['preco_custo']??0),'price'=>(float)$data['preco_venda'],'promo'=>$n('preco_promocional'),'stock_min'=>(float)($data['estoque_minimo']??0),'stock_max'=>(float)($data['estoque_maximo']??0),'weight'=>$n('peso'),'height'=>$n('altura'),'width'=>$n('largura'),'length'=>$n('comprimento'),'ncm'=>$n('ncm'),'cest'=>$n('cest'),'cfop'=>$n('cfop'),'origin'=>$n('origem'),'taxation'=>$n('tributacao'),'warranty'=>$n('garantia_meses'),'negative_stock'=>!empty($data['permite_estoque_negativo'])?'true':'false','launch'=>!empty($data['lancamento'])?'true':'false','featured'=>!empty($data['destaque'])?'true':'false','status'=>!isset($data['situacao'])||!empty($data['situacao'])?1:0]; }
    private function assertReferences(int $companyId,array $data): void { if(!$this->one('SELECT idcategoria FROM categoria_produto WHERE idempresa=:company_id AND idcategoria=:id AND situacao=1',['company_id'=>$companyId,'id'=>(int)$data['idcategoria']]))throw new InvalidArgumentException('Categoria invalida');if(!empty($data['idmarca'])&&!$this->one('SELECT idmarca FROM marca WHERE idempresa=:company_id AND idmarca=:id AND situacao=1',['company_id'=>$companyId,'id'=>(int)$data['idmarca']]))throw new InvalidArgumentException('Marca invalida'); }
    private function syncRelations(int $companyId,int $productId,array $data): void { $this->pdo->prepare('DELETE FROM produto_fornecedor WHERE idempresa=:company_id AND idproduto=:product_id')->execute(['company_id'=>$companyId,'product_id'=>$productId]);$ids=array_values(array_unique(array_filter([(int)($data['idfornecedor_principal']??0),(int)($data['idfornecedor_secundario']??0)])));foreach($ids as $index=>$id){if(!$this->one('SELECT idfornecedor FROM fornecedor WHERE idempresa=:company_id AND idfornecedor=:id AND situacao=1',['company_id'=>$companyId,'id'=>$id]))throw new InvalidArgumentException('Fornecedor invalido');$this->pdo->prepare('INSERT INTO produto_fornecedor(idempresa,idproduto,idfornecedor,principal,codigo_fornecedor) VALUES(:company_id,:product_id,:supplier,:primary,:code)')->execute(['company_id'=>$companyId,'product_id'=>$productId,'supplier'=>$id,'primary'=>$index===0?'true':'false','code'=>$index===0?($data['codigo_fornecedor']??null):null]);}$this->pdo->prepare('DELETE FROM produto_imagem WHERE idempresa=:company_id AND idproduto=:product_id')->execute(['company_id'=>$companyId,'product_id'=>$productId]);$images=array_values(array_filter($data['imagens']??[],fn($url)=>filter_var($url,FILTER_VALIDATE_URL)));foreach($images as $index=>$url)$this->pdo->prepare('INSERT INTO produto_imagem(idempresa,idproduto,url,principal,ordem) VALUES(:company_id,:product_id,:url,:primary,:sort)')->execute(['company_id'=>$companyId,'product_id'=>$productId,'url'=>$url,'primary'=>$index===0?'true':'false','sort'=>$index]); }
    private function initialStock(int $companyId,int $actorId,int $productId,array $data): void { $quantity=(float)($data['estoque_inicial']??0);if($quantity<=0)return;if(empty($data['idfilial_inicial']))throw new InvalidArgumentException('Filial inicial e obrigatoria');$branch=(int)$data['idfilial_inicial'];$this->pdo->prepare('INSERT INTO estoque(idempresa,idfilial,idproduto,quantidade,situacao) VALUES(:company_id,:branch_id,:product_id,:quantity,1)')->execute(['company_id'=>$companyId,'branch_id'=>$branch,'product_id'=>$productId,'quantity'=>$quantity]);$this->pdo->prepare("INSERT INTO movimentacao_estoque(idempresa,idfilial,idproduto,idusuario,tipo,quantidade,observacao,situacao) VALUES(:company_id,:branch_id,:product_id,:actor_id,1,:quantity,'Estoque inicial',1)")->execute(['company_id'=>$companyId,'branch_id'=>$branch,'product_id'=>$productId,'actor_id'=>$actorId,'quantity'=>$quantity]); }
    private function options(int $companyId): array { return ['categories'=>$this->all('SELECT idcategoria id,nome FROM categoria_produto WHERE idempresa=:company_id AND situacao=1 ORDER BY nome',['company_id'=>$companyId]),'brands'=>$this->all('SELECT idmarca id,nome FROM marca WHERE idempresa=:company_id AND situacao=1 ORDER BY nome',['company_id'=>$companyId]),'suppliers'=>$this->all("SELECT idfornecedor id,COALESCE(nome_fantasia,razao_social) nome FROM fornecedor WHERE idempresa=:company_id AND situacao=1 ORDER BY nome",['company_id'=>$companyId]),'branches'=>$this->all('SELECT idfilial id,nome FROM filial WHERE idempresa=:company_id AND situacao=1 ORDER BY matriz DESC,nome',['company_id'=>$companyId])]; }
    private function audit(int $companyId,int $actorId,int $productId,string $action,?array $before,?array $after,?string $ip,?string $agent): void { $this->pdo->prepare("INSERT INTO auditoria(idempresa,idusuario,origem_usuario,tabela,registro_id,acao,valores_anteriores,valores_novos,ip,dispositivo) VALUES(:company_id,:actor_id,'empresa','produto',:product_id,:action,:before::jsonb,:after::jsonb,:ip,:device)")->execute(['company_id'=>$companyId,'actor_id'=>$actorId,'product_id'=>$productId,'action'=>$action,'before'=>$before?json_encode($before):null,'after'=>$after?json_encode($after):null,'ip'=>$ip,'device'=>$agent?substr($agent,0,150):null]); }
    private function transaction(callable $callback): mixed { $this->pdo->beginTransaction();try{$result=$callback();$this->pdo->commit();return $result;}catch(Throwable $exception){$this->pdo->rollBack();throw $exception;} }
    private function one(string $sql,array $params): array { $s=$this->pdo->prepare($sql);$s->execute($params);return $s->fetch(PDO::FETCH_ASSOC)?:[]; }
    private function all(string $sql,array $params): array { $s=$this->pdo->prepare($sql);$s->execute($params);return $s->fetchAll(PDO::FETCH_ASSOC); }
}
