<?php

namespace App\Modules\Finance\Repositories;

use App\Infrastructures\Config\Database;
use InvalidArgumentException;
use PDO;
use Throwable;

final class FinanceRepository
{
    private PDO $pdo;
    public function __construct(){$this->pdo=Database::getInstance();}
    public function index(int $companyId,array $filters):array
    {
        [$start,$end,$previousStart,$previousEnd]=$this->range($filters);$params=['company_id'=>$companyId,'start'=>$start,'end'=>$end,'previous_start'=>$previousStart,'previous_end'=>$previousEnd];
        $kpis=$this->one("SELECT COALESCE((SELECT SUM(valor+juros+multa-desconto) FROM conta_receber WHERE idempresa=:company_id AND situacao=2),0) received,COALESCE((SELECT SUM(valor+juros+multa-desconto) FROM conta_pagar WHERE idempresa=:company_id AND situacao=2),0) paid,COALESCE((SELECT SUM(valor+juros+multa-desconto) FROM conta_receber WHERE idempresa=:company_id AND situacao=1),0) receivable,COALESCE((SELECT SUM(valor+juros+multa-desconto) FROM conta_pagar WHERE idempresa=:company_id AND situacao=1),0) payable,COALESCE((SELECT SUM(saldo_inicial) FROM conta_bancaria WHERE idempresa=:company_id AND situacao=1),0) bank_initial,COALESCE((SELECT SUM(valor+juros+multa-desconto) FROM conta_receber WHERE idempresa=:company_id AND situacao=2 AND data_recebimento BETWEEN date_trunc('month',CURRENT_DATE)::date AND CURRENT_DATE),0) month_revenue,COALESCE((SELECT SUM(valor+juros+multa-desconto) FROM conta_pagar WHERE idempresa=:company_id AND situacao=2 AND data_pagamento BETWEEN date_trunc('month',CURRENT_DATE)::date AND CURRENT_DATE),0) month_expense,COALESCE((SELECT SUM(valor+juros+multa-desconto) FROM conta_receber WHERE idempresa=:company_id AND situacao=2 AND data_recebimento BETWEEN :previous_start AND :previous_end),0) previous_revenue,COALESCE((SELECT SUM(valor+juros+multa-desconto) FROM conta_pagar WHERE idempresa=:company_id AND situacao=2 AND data_pagamento BETWEEN :previous_start AND :previous_end),0) previous_expense",$params);
        $kpis['current_balance']=(float)$kpis['bank_initial']+(float)$kpis['received']-(float)$kpis['paid'];$kpis['projected_balance']=$kpis['current_balance']+(float)$kpis['receivable']-(float)$kpis['payable'];$kpis['cash_flow']=(float)$kpis['month_revenue']-(float)$kpis['month_expense'];
        $where=['x.idempresa=:company_id'];$listParams=['company_id'=>$companyId];foreach(['idfilial'=>'branch','idcategoria_financeira'=>'category','idcentro_custo'=>'cost_center','idconta_bancaria'=>'bank','situacao'=>'status']as$col=>$key)if(($filters[$key]??'')!==''){$where[]="x.$col=:$key";$listParams[$key]=(int)$filters[$key];}if(($filters['type']??'')!==''){$where[]='x.type=:type';$listParams['type']=$filters['type'];}if(($filters['payment']??'')!==''){$where[]='x.forma_pagamento=:payment';$listParams['payment']=$filters['payment'];}if(!empty($filters['q'])){$where[]='(x.descricao ILIKE :q OR x.documento ILIKE :q OR x.party ILIKE :q OR x.categoria ILIKE :q)';$listParams['q']='%'.trim($filters['q']).'%';}
        $union="SELECT 'expense' type,cp.idconta_pagar id,cp.idempresa,cp.idfilial,cp.idcategoria_financeira,cp.idcentro_custo,cp.idconta_bancaria,cp.descricao,cp.valor,cp.data_vencimento due_date,cp.data_pagamento settlement_date,cp.situacao,cp.forma_pagamento,cp.documento,cp.observacoes,cp.juros,cp.desconto,cp.multa,cp.parcela_numero,cp.parcelas_total,cp.recorrente,cp.criado_em,f.nome filial,fc.nome categoria,cc.nome centro_custo,cb.banco conta,COALESCE(fr.nome_fantasia,fr.razao_social) party FROM conta_pagar cp LEFT JOIN filial f ON f.idempresa=cp.idempresa AND f.idfilial=cp.idfilial LEFT JOIN financeiro_categoria fc ON fc.idcategoria_financeira=cp.idcategoria_financeira LEFT JOIN centro_custo cc ON cc.idcentro_custo=cp.idcentro_custo LEFT JOIN conta_bancaria cb ON cb.idconta_bancaria=cp.idconta_bancaria LEFT JOIN fornecedor fr ON fr.idempresa=cp.idempresa AND fr.idfornecedor=cp.idfornecedor UNION ALL SELECT 'revenue',cr.idconta_receber,cr.idempresa,cr.idfilial,cr.idcategoria_financeira,cr.idcentro_custo,cr.idconta_bancaria,cr.descricao,cr.valor,cr.data_vencimento,cr.data_recebimento,cr.situacao,cr.forma_pagamento,cr.documento,cr.observacoes,cr.juros,cr.desconto,cr.multa,cr.parcela_numero,cr.parcelas_total,cr.recorrente,cr.criado_em,f.nome,fc.nome,cc.nome,cb.banco,cl.nome FROM conta_receber cr LEFT JOIN filial f ON f.idempresa=cr.idempresa AND f.idfilial=cr.idfilial LEFT JOIN financeiro_categoria fc ON fc.idcategoria_financeira=cr.idcategoria_financeira LEFT JOIN centro_custo cc ON cc.idcentro_custo=cr.idcentro_custo LEFT JOIN conta_bancaria cb ON cb.idconta_bancaria=cr.idconta_bancaria LEFT JOIN cliente cl ON cl.idempresa=cr.idempresa AND cl.idcliente=cr.idcliente";
        $movements=$this->all("SELECT x.*,(x.valor+x.juros+x.multa-x.desconto) total,CASE WHEN x.situacao=1 AND x.due_date<CURRENT_DATE THEN 'overdue' WHEN x.situacao=1 THEN 'pending' WHEN x.situacao=2 THEN 'settled' ELSE 'cancelled' END status_key FROM ($union) x WHERE ".implode(' AND ',$where).' ORDER BY x.due_date DESC,x.criado_em DESC LIMIT 200',$listParams);
        $chart=$this->all("WITH days AS (SELECT generate_series(:start::date,:end::date,'1 day')::date AS date_key),r AS (SELECT data_vencimento AS date_key,SUM(valor+juros+multa-desconto) value FROM conta_receber WHERE idempresa=:company_id AND situacao<>3 AND data_vencimento BETWEEN :start AND :end GROUP BY 1),p AS (SELECT data_vencimento AS date_key,SUM(valor+juros+multa-desconto) value FROM conta_pagar WHERE idempresa=:company_id AND situacao<>3 AND data_vencimento BETWEEN :start AND :end GROUP BY 1) SELECT d.date_key AS day,COALESCE(r.value,0) revenue,COALESCE(p.value,0) expense,COALESCE(r.value,0)-COALESCE(p.value,0) balance FROM days d LEFT JOIN r ON r.date_key=d.date_key LEFT JOIN p ON p.date_key=d.date_key ORDER BY d.date_key",$params);
        $payable=$this->one("SELECT COALESCE(SUM(valor+juros+multa-desconto) FILTER(WHERE situacao=1),0) pending,COUNT(*) FILTER(WHERE situacao=1 AND data_vencimento=CURRENT_DATE) today,COUNT(*) FILTER(WHERE situacao=1 AND data_vencimento=CURRENT_DATE+1) tomorrow,COUNT(*) FILTER(WHERE situacao=1 AND data_vencimento<CURRENT_DATE) overdue FROM conta_pagar WHERE idempresa=:company_id",['company_id'=>$companyId]);
        $receivable=$this->one("SELECT COALESCE(SUM(valor+juros+multa-desconto) FILTER(WHERE situacao=1),0) pending,COALESCE(SUM(valor+juros+multa-desconto) FILTER(WHERE situacao=2 AND data_recebimento=CURRENT_DATE),0) today,COUNT(*) FILTER(WHERE situacao=1 AND data_vencimento<CURRENT_DATE) overdue,COALESCE(SUM(valor+juros+multa-desconto) FILTER(WHERE situacao=1 AND data_vencimento>=CURRENT_DATE),0) expected FROM conta_receber WHERE idempresa=:company_id",['company_id'=>$companyId]);
        $banks=$this->all("SELECT cb.*,cb.saldo_inicial+COALESCE(r.received,0)-COALESCE(p.paid,0) balance,GREATEST(r.last_movement,p.last_movement) last_movement FROM conta_bancaria cb LEFT JOIN (SELECT idconta_bancaria,SUM(valor+juros+multa-desconto) received,MAX(data_recebimento) last_movement FROM conta_receber WHERE idempresa=:company_id AND situacao=2 GROUP BY idconta_bancaria) r ON r.idconta_bancaria=cb.idconta_bancaria LEFT JOIN (SELECT idconta_bancaria,SUM(valor+juros+multa-desconto) paid,MAX(data_pagamento) last_movement FROM conta_pagar WHERE idempresa=:company_id AND situacao=2 GROUP BY idconta_bancaria) p ON p.idconta_bancaria=cb.idconta_bancaria WHERE cb.idempresa=:company_id AND cb.situacao=1 ORDER BY cb.banco",['company_id'=>$companyId]);
        $cards=$this->all("SELECT ce.*,COALESCE(cp.invoice,0) invoice,ce.limite-COALESCE(cp.invoice,0) available,(date_trunc('month',CURRENT_DATE)+INTERVAL '1 month'+(LEAST(ce.dia_vencimento,28)-1)*INTERVAL '1 day')::date next_due FROM cartao_empresa ce LEFT JOIN (SELECT forma_pagamento,SUM(valor+juros+multa-desconto) invoice FROM conta_pagar WHERE idempresa=:company_id AND situacao=1 GROUP BY forma_pagamento) cp ON cp.forma_pagamento='cartao:'||ce.idcartao WHERE ce.idempresa=:company_id AND ce.situacao=1",['company_id'=>$companyId]);
        $meta=$this->one('SELECT meta_mensal FROM configuracao_financeira WHERE idempresa=:company_id',['company_id'=>$companyId]);$goal=(float)($meta['meta_mensal']??0);$goalPercent=$goal>0?min(100,((float)$kpis['month_revenue']/$goal)*100):0;
        $insights=[];if((float)$kpis['projected_balance']<0)$insights[]=['tone'=>'danger','title'=>'Saldo projetado negativo','description'=>'Os compromissos previstos superam os recursos disponiveis.'];if((float)$kpis['previous_expense']>0&&$kpis['month_expense']>$kpis['previous_expense'])$insights[]=['tone'=>'warning','title'=>'Despesas em alta','description'=>'As despesas superaram o periodo anterior.'];if((int)$payable['overdue']>0)$insights[]=['tone'=>'warning','title'=>'Contas vencidas','description'=>$payable['overdue'].' despesas precisam de atencao.'];if(!$insights)$insights[]=['tone'=>'success','title'=>'Operacao sob controle','description'=>'Nenhum alerta financeiro critico foi identificado.'];
        return ['period'=>['start'=>$start,'end'=>$end],'kpis'=>$kpis,'chart'=>$chart,'movements'=>$movements,'payable'=>$payable,'receivable'=>$receivable,'banks'=>$banks,'cards'=>$cards,'goal'=>['value'=>$goal,'percentage'=>$goalPercent],'insights'=>$insights,'options'=>$this->options($companyId)];
    }

    public function show(int $companyId,string $type,int $id):?array
    {
        [$table,$pk,$date]=$this->mapping($type);$item=$this->one("SELECT x.*,fc.nome categoria,cc.nome centro_custo,cb.banco conta,f.nome filial FROM $table x LEFT JOIN financeiro_categoria fc ON fc.idcategoria_financeira=x.idcategoria_financeira LEFT JOIN centro_custo cc ON cc.idcentro_custo=x.idcentro_custo LEFT JOIN conta_bancaria cb ON cb.idconta_bancaria=x.idconta_bancaria LEFT JOIN filial f ON f.idempresa=x.idempresa AND f.idfilial=x.idfilial WHERE x.idempresa=:company_id AND x.$pk=:id",['company_id'=>$companyId,'id'=>$id]);if(!$item)return null;$item['type']=$type;$item['settlement_date']=$item[$date];$item['attachments']=$this->all('SELECT idanexo,nome,url,criado_em FROM anexo_financeiro WHERE idempresa=:company_id AND tipo_lancamento=:type AND idlancamento=:id ORDER BY criado_em DESC',['company_id'=>$companyId,'type'=>$type==='revenue'?1:2,'id'=>$id]);$item['history']=$this->all("SELECT idauditoria,acao,valores_anteriores,valores_novos,criado_em FROM auditoria WHERE idempresa=:company_id AND tabela=:table AND registro_id=:id ORDER BY criado_em DESC LIMIT 30",['company_id'=>$companyId,'table'=>$table,'id'=>$id]);return $item;
    }

    public function create(int $companyId,int $actorId,string $type,array $data,?string $ip,?string $agent):array
    {
        return $this->transaction(function()use($companyId,$actorId,$type,$data,$ip,$agent){[$table,$pk]=$this->mapping($type);$this->assertReferences($companyId,$type,$data);$count=(int)($data['parcelas_total']??1);$amount=round((float)$data['valor']/$count,2);$ids=[];for($i=1;$i<=$count;$i++){$value=$i===$count?(float)$data['valor']-$amount*($count-1):$amount;$due=(new \DateTimeImmutable($data['data_vencimento']))->modify('+'.($i-1).' month')->format('Y-m-d');$partyColumn=$type==='revenue'?'idcliente':'idfornecedor';$sql="INSERT INTO $table(idempresa,idfilial,$partyColumn,descricao,valor,data_vencimento,situacao,idcategoria_financeira,idcentro_custo,idconta_bancaria,forma_pagamento,documento,observacoes,juros,desconto,multa,parcela_numero,parcelas_total,recorrente) VALUES(:company_id,:branch,:party,:description,:value,:due,1,:category,:cost_center,:bank,:payment,:document,:notes,:interest,:discount,:fine,:installment,:installments,:recurring) RETURNING $pk";$s=$this->pdo->prepare($sql);$s->execute($this->params($companyId,$data)+['party'=>!empty($data[$partyColumn])?(int)$data[$partyColumn]:null,'value'=>$value,'due'=>$due,'installment'=>$i,'installments'=>$count]);$id=(int)$s->fetchColumn();$ids[]=$id;$this->audit($companyId,$actorId,$table,$id,'criar',null,['descricao'=>$data['descricao'],'parcela'=>$i],$ip,$agent);}return $ids;});
    }

    public function update(int $companyId,int $actorId,string $type,int $id,array $data,?string $ip,?string $agent):void
    {
        [$table,$pk]=$this->mapping($type);$before=$this->one("SELECT descricao,valor,situacao FROM $table WHERE idempresa=:company_id AND $pk=:id",['company_id'=>$companyId,'id'=>$id]);if(!$before)throw new InvalidArgumentException('Lancamento nao encontrado');$this->assertReferences($companyId,$type,$data);$partyColumn=$type==='revenue'?'idcliente':'idfornecedor';$params=$this->params($companyId,$data)+['party'=>!empty($data[$partyColumn])?(int)$data[$partyColumn]:null,'value'=>(float)$data['valor'],'due'=>$data['data_vencimento'],'id'=>$id];$this->pdo->prepare("UPDATE $table SET idfilial=:branch,$partyColumn=:party,descricao=:description,valor=:value,data_vencimento=:due,idcategoria_financeira=:category,idcentro_custo=:cost_center,idconta_bancaria=:bank,forma_pagamento=:payment,documento=:document,observacoes=:notes,juros=:interest,desconto=:discount,multa=:fine,recorrente=:recurring,atualizado_em=CURRENT_TIMESTAMP WHERE idempresa=:company_id AND $pk=:id")->execute($params);$this->audit($companyId,$actorId,$table,$id,'editar',$before,['descricao'=>$data['descricao']],$ip,$agent);
    }

    public function setStatus(int $companyId,int $actorId,string $type,int $id,int $status,?string $ip,?string $agent):void{[$table,$pk,$date]=$this->mapping($type);$s=$this->pdo->prepare("UPDATE $table SET situacao=:status,$date=CASE WHEN :status=2 THEN CURRENT_DATE ELSE NULL END,atualizado_em=CURRENT_TIMESTAMP WHERE idempresa=:company_id AND $pk=:id");$s->execute(['status'=>$status,'company_id'=>$companyId,'id'=>$id]);if(!$s->rowCount())throw new InvalidArgumentException('Lancamento nao encontrado');$this->audit($companyId,$actorId,$table,$id,$status===2?($type==='revenue'?'receber':'pagar'):($status===3?'cancelar':'reabrir'),null,['situacao'=>$status],$ip,$agent);}
    public function duplicate(int $companyId,int $actorId,string $type,int $id,?string $ip,?string $agent):array{$item=$this->show($companyId,$type,$id);if(!$item)throw new InvalidArgumentException('Lancamento nao encontrado');$item['descricao'].=' - Copia';$item['data_vencimento']=(new \DateTimeImmutable())->modify('+1 day')->format('Y-m-d');$item['parcelas_total']=1;return $this->create($companyId,$actorId,$type,$item,$ip,$agent);}
    private function params(int $companyId,array $data):array{return ['company_id'=>$companyId,'branch'=>!empty($data['idfilial'])?(int)$data['idfilial']:null,'description'=>trim($data['descricao']),'category'=>(int)$data['idcategoria_financeira'],'cost_center'=>(int)$data['idcentro_custo'],'bank'=>(int)$data['idconta_bancaria'],'payment'=>$data['forma_pagamento']??null,'document'=>$data['documento']??null,'notes'=>$data['observacoes']??null,'interest'=>(float)($data['juros']??0),'discount'=>(float)($data['desconto']??0),'fine'=>(float)($data['multa']??0),'recurring'=>!empty($data['recorrente'])?'true':'false'];}
    private function assertReferences(int $companyId,string $type,array $data):void{if(!$this->one('SELECT idcategoria_financeira FROM financeiro_categoria WHERE idempresa=:company_id AND idcategoria_financeira=:id AND tipo=:type AND situacao=1',['company_id'=>$companyId,'id'=>(int)$data['idcategoria_financeira'],'type'=>$type==='revenue'?1:2]))throw new InvalidArgumentException('Categoria invalida');foreach([['centro_custo','idcentro_custo'],['conta_bancaria','idconta_bancaria']]as[$table,$field])if(!$this->one("SELECT $field FROM $table WHERE idempresa=:company_id AND $field=:id AND situacao=1",['company_id'=>$companyId,'id'=>(int)$data[$field]]))throw new InvalidArgumentException('Referencia financeira invalida');}
    private function options(int $companyId):array{return ['categories'=>$this->all('SELECT idcategoria_financeira id,nome,tipo FROM financeiro_categoria WHERE idempresa=:company_id AND situacao=1 ORDER BY tipo,nome',['company_id'=>$companyId]),'cost_centers'=>$this->all('SELECT idcentro_custo id,nome FROM centro_custo WHERE idempresa=:company_id AND situacao=1 ORDER BY nome',['company_id'=>$companyId]),'banks'=>$this->all('SELECT idconta_bancaria id,banco||\' - \'||conta nome FROM conta_bancaria WHERE idempresa=:company_id AND situacao=1 ORDER BY banco',['company_id'=>$companyId]),'branches'=>$this->all('SELECT idfilial id,nome FROM filial WHERE idempresa=:company_id AND situacao=1 ORDER BY matriz DESC,nome',['company_id'=>$companyId]),'customers'=>$this->all('SELECT idcliente id,nome FROM cliente WHERE idempresa=:company_id AND situacao=1 ORDER BY nome LIMIT 500',['company_id'=>$companyId]),'suppliers'=>$this->all('SELECT idfornecedor id,COALESCE(nome_fantasia,razao_social) nome FROM fornecedor WHERE idempresa=:company_id AND situacao=1 ORDER BY nome LIMIT 500',['company_id'=>$companyId])];}
    /**
     * Anexos do lancamento (boleto, nota, comprovante). O arquivo em si fica
     * no disco (fora do public/); aqui guardamos so o nome e o caminho
     * relativo, sempre amarrados a empresa e ao lancamento.
     */
    public function addAttachment(int $companyId,int $actorId,string $type,int $id,string $name,string $path,?string $ip,?string $agent):int
    {
        $this->assertEntry($companyId,$type,$id);
        $s=$this->pdo->prepare('INSERT INTO anexo_financeiro(idempresa,tipo_lancamento,idlancamento,nome,url) VALUES(:company_id,:type,:id,:name,:path) RETURNING idanexo');
        $s->execute(['company_id'=>$companyId,'type'=>$this->attachmentType($type),'id'=>$id,'name'=>$name,'path'=>$path]);
        $attachmentId=(int)$s->fetchColumn();
        [$table]=$this->mapping($type);
        $this->audit($companyId,$actorId,$table,$id,'anexar',null,['anexo'=>$name],$ip,$agent);
        return $attachmentId;
    }

    public function attachment(int $companyId,string $type,int $id,int $attachmentId):array
    {
        $item=$this->one('SELECT idanexo,nome,url FROM anexo_financeiro WHERE idempresa=:company_id AND tipo_lancamento=:type AND idlancamento=:id AND idanexo=:attachment',['company_id'=>$companyId,'type'=>$this->attachmentType($type),'id'=>$id,'attachment'=>$attachmentId]);
        if(!$item)throw new InvalidArgumentException('Anexo nao encontrado');
        return $item;
    }

    public function removeAttachment(int $companyId,int $actorId,string $type,int $id,int $attachmentId,?string $ip,?string $agent):string
    {
        $item=$this->attachment($companyId,$type,$id,$attachmentId);
        $this->pdo->prepare('DELETE FROM anexo_financeiro WHERE idempresa=:company_id AND idanexo=:attachment')->execute(['company_id'=>$companyId,'attachment'=>$attachmentId]);
        [$table]=$this->mapping($type);
        $this->audit($companyId,$actorId,$table,$id,'remover_anexo',['anexo'=>$item['nome']],null,$ip,$agent);
        return (string)$item['url'];
    }

    private function assertEntry(int $companyId,string $type,int $id):void{[$table,$pk]=$this->mapping($type);if(!$this->one("SELECT 1 FROM $table WHERE idempresa=:company_id AND $pk=:id",['company_id'=>$companyId,'id'=>$id]))throw new InvalidArgumentException('Lancamento nao encontrado');}
    private function attachmentType(string $type):int{return $type==='revenue'?1:2;}
    private function mapping(string $type):array{return $type==='revenue'?['conta_receber','idconta_receber','data_recebimento']:['conta_pagar','idconta_pagar','data_pagamento'];}
    private function range(array $filters):array{$pattern='/^\d{4}-\d{2}-\d{2}$/';$rawStart=$filters['start']??null;$rawEnd=$filters['end']??null;if($rawStart&&$rawEnd&&preg_match($pattern,(string)$rawStart)&&preg_match($pattern,(string)$rawEnd)){$start=new \DateTimeImmutable((string)$rawStart);$end=new \DateTimeImmutable((string)$rawEnd);if($end<$start){[$start,$end]=[$end,$start];}$days=(int)$start->diff($end)->days;$prevEnd=$start->modify('-1 day');$prevStart=$prevEnd->modify("-$days days");return[$start->format('Y-m-d'),$end->format('Y-m-d'),$prevStart->format('Y-m-d'),$prevEnd->format('Y-m-d')];}return $this->period($filters['period']??'30d');}
    private function period(string $period):array{$end=new \DateTimeImmutable('today');$days=match($period){'today'=>0,'7d'=>6,'90d'=>89,'year'=>(int)$end->format('z'),default=>29};$start=$end->modify("-$days days");$prevEnd=$start->modify('-1 day');$prevStart=$prevEnd->modify("-$days days");return[$start->format('Y-m-d'),$end->format('Y-m-d'),$prevStart->format('Y-m-d'),$prevEnd->format('Y-m-d')];}
    private function audit(int $companyId,int $actorId,string $table,int $id,string $action,?array $before,?array $after,?string $ip,?string $agent):void{$this->pdo->prepare("INSERT INTO auditoria(idempresa,idusuario,origem_usuario,tabela,registro_id,acao,valores_anteriores,valores_novos,ip,dispositivo) VALUES(:company_id,:actor_id,'empresa',:table,:id,:action,:before::jsonb,:after::jsonb,:ip,:device)")->execute(['company_id'=>$companyId,'actor_id'=>$actorId,'table'=>$table,'id'=>$id,'action'=>$action,'before'=>$before?json_encode($before):null,'after'=>$after?json_encode($after):null,'ip'=>$ip,'device'=>$agent?substr($agent,0,150):null]);}
    private function transaction(callable $callback):mixed{$this->pdo->beginTransaction();try{$result=$callback();$this->pdo->commit();return$result;}catch(Throwable $e){$this->pdo->rollBack();throw$e;}}
    private function one(string $sql,array $params):array{$s=$this->pdo->prepare($sql);$s->execute($params);return$s->fetch(PDO::FETCH_ASSOC)?:[];}
    private function all(string $sql,array $params):array{$s=$this->pdo->prepare($sql);$s->execute($params);return$s->fetchAll(PDO::FETCH_ASSOC);}
}
